# Generated by Django 4.2.2 on 2023-07-31 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('start_date', models.DateTimeField(verbose_name='Fecha del inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha del fin')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creado')),
            ],
            options={
                'verbose_name': 'Lista personalizada',
                'verbose_name_plural': 'Listas personalizadas',
            },
        ),
        migrations.CreateModel(
            name='CustomsListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Agregado')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_list_item', to='catalogue.content', verbose_name='Producto')),
                ('custom_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_list_items', to='lists.customslist', verbose_name='Producto de la lista')),
            ],
            options={
                'verbose_name': 'Producto de la lista',
                'verbose_name_plural': 'Productos de las listas',
            },
        ),
    ]
