# Generated by Django 4.2 on 2023-07-13 02:23

import apps.category.actions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=None, upload_to=apps.category.actions.generate_category_photo_path, verbose_name='Foto de la Categoria'),
            preserve_default=False,
        ),
    ]
