# Generated by Django 4.2 on 2023-07-13 02:24

import apps.category.actions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_first_name_actor_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(null=True, upload_to=apps.category.actions.generate_category_photo_path, verbose_name='Foto de la Categoria'),
        ),
    ]
