# Generated by Django 4.2.2 on 2023-07-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluseraccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='email',
        ),
        migrations.AddField(
            model_name='historicaluseraccount',
            name='nick_name',
            field=models.CharField(db_index=True, default=None, max_length=255, verbose_name='Alias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='nick_name',
            field=models.CharField(default=None, max_length=255, unique=True, verbose_name='Alias'),
            preserve_default=False,
        ),
    ]
