# Generated by Django 4.2.2 on 2023-07-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_historicaluseraccount_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluseraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='historicaluseraccount',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='historicaluseraccount',
            name='nick_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='nick_name',
        ),
        migrations.AddField(
            model_name='historicaluseraccount',
            name='username',
            field=models.CharField(db_index=True, default=None, max_length=255, verbose_name='Nombre de Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default=None, max_length=255, unique=True, verbose_name='Nombre de Usuario'),
            preserve_default=False,
        ),
    ]
