export const CATEGORYURL = 'http://localhost:8000/api/category/'
export const CATALOGUEURL = 'http://localhost:8000/api/catalogue/'
export const SEARCHLISTURL = 'http://localhost:8000/api/lists/treanding-searches/'
export const GENDERSLISTURL = 'http://localhost:8000/api/category/genders/'
export const ACTORSLISTURL = 'http://localhost:8000/api/category/actors/'