# Generated by Django 4.2.2 on 2023-09-03 03:36

import apps.catalogue.helpers
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\n        Se llena automaticamente si no se llena, a travez de la ruta del contenido.\n        ', max_length=100, unique=True, verbose_name='Nombre')),
                ('photo', models.ImageField(help_text='\n        Imagen que saldra en el catalogo.\n        ', upload_to=apps.catalogue.helpers.generate_content_photo_path, verbose_name='Foto de Portada')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('path', models.CharField(blank=True, help_text='\n        Este campo es para especificar la ruta de la carpeta de la pelicula o serie pero hay que tener en cuenta los siguientes puntos:\n        En caso de los contenidos con un solo video:\n            . Si se pone la ruta de la carpeta donde esta el contenido detecta automaticamente el archivo de video dentro de la ruta.\n            . De esa ruta es de donde se va a leer el video que ve el usuario.\n        En caso de los contenidos con varios videos:\n            . En este caso se pone la ruta de la carpeta donde se encuentra el contenido pero esto es solo para saber donde esta el contenido.\n            . Se puede dejar en blanco aunque es recomendable usarlo para saber la ubicacion del contenido.\n        ', max_length=255, null=True, verbose_name='Ruta en disco duro')),
                ('format', models.CharField(blank=True, help_text='\n        No es obligatorio y en caso de llenar la ruta de la carpeta y sea un slo fichero de video este campo se llenara automaticamente con la informacion del archivo de video.\n        ', max_length=50, null=True, verbose_name='Formato')),
                ('size', models.CharField(blank=True, help_text='\n        No es obligatorio y en caso de llenar la ruta de la carpeta y sea un solo fichero de video este campo se llenara automaticamente con la informacion del archivo de video.\n        ', max_length=10, null=True, verbose_name='Tamaño')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Fecha completa de Estreno')),
                ('release_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1900)], verbose_name='Año de Estreno')),
                ('is_subtitled', models.BooleanField(default=False, verbose_name='Esta Subtitulada')),
                ('is_spanish', models.BooleanField(default=False, verbose_name='Esta en Español')),
                ('subtitle', models.FileField(blank=True, null=True, upload_to=apps.catalogue.helpers.generate_content_subtitule_path, verbose_name='Subtitulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('platform', models.CharField(blank=True, max_length=100, verbose_name='Plataforma')),
                ('countrie', models.CharField(blank=True, choices=[('Afghanistan', 'Afghanistan'), ('Åland Islands', 'Åland Islands'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('American Samoa', 'American Samoa'), ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Anguilla', 'Anguilla'), ('Antarctica', 'Antarctica'), ('Antigua and Barbuda', 'Antigua And Barbuda'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Aruba', 'Aruba'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaijan', 'Azerbaijan'), ('Bahamas', 'Bahamas'), ('Bahrain', 'Bahrain'), ('Bangladesh', 'Bangladesh'), ('Barbados', 'Barbados'), ('Belarus', 'Belarus'), ('Belgium', 'Belgium'), ('Belize', 'Belize'), ('Benin', 'Benin'), ('Bermuda', 'Bermuda'), ('Bhutan', 'Bhutan'), ('Bolivia (Plurinational State of)', 'Bolivia'), ('Bonaire, Sint Eustatius and Saba', 'Bonaire'), ('Bosnia and Herzegovina', 'Bosnia And Herzegovina'), ('Botswana', 'Botswana'), ('Bouvet Island', 'Bouvet Island'), ('Brazil', 'Brazil'), ('British Indian Ocean Territory', 'British Indian Ocean Territory'), ('Brunei Darussalam', 'Brunei Darussalam'), ('Bulgaria', 'Bulgaria'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Cabo Verde', 'Cabo Verde'), ('Cambodia', 'Cambodia'), ('Cameroon', 'Cameroon'), ('Canada', 'Canada'), ('Cayman Islands', 'Cayman Islands'), ('Central African Republic', 'Central African Republic'), ('Chad', 'Chad'), ('Chile', 'Chile'), ('China', 'China'), ('Christmas Island', 'Christmas Island'), ('Cocos (Keeling) Islands', 'Cocos Islands'), ('Colombia', 'Colombia'), ('Comoros', 'Comoros'), ('Congo', 'Congo'), ('Democratic Republic of the Congo', 'Democratic Republic Of The Congo'), ('Cook Islands', 'Cook Islands'), ('Costa Rica', 'Costa Rica'), ("Côte d'Ivoire", 'Côte Divoire'), ('Croatia', 'Croatia'), ('Cuba', 'Cuba'), ('Curaçao', 'Curaçao'), ('Cyprus', 'Cyprus'), ('Czechia', 'Czechia'), ('Denmark', 'Denmark'), ('Djibouti', 'Djibouti'), ('Dominica', 'Dominica'), ('Dominican Republic', 'Dominican Republic'), ('Ecuador', 'Ecuador'), ('Egypt', 'Egypt'), ('El Salvador', 'El Salvador'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Eritrea', 'Eritrea'), ('Estonia', 'Estonia'), ('Eswatini', 'Eswatini'), ('Ethiopia', 'Ethiopia'), ('Falkland Islands (Malvinas)', 'Falkland Islands'), ('Faroe Islands', 'Faroe Islands'), ('Fiji', 'Fiji'), ('Finland', 'Finland'), ('France', 'France'), ('French Guiana', 'French Guiana'), ('French Polynesia', 'French Polynesia'), ('French Southern Territories', 'French Southern Territories'), ('Gabon', 'Gabon'), ('Gambia', 'Gambia'), ('Georgia', 'Georgia'), ('Germany', 'Germany'), ('Ghana', 'Ghana'), ('Gibraltar', 'Gibraltar'), ('Greece', 'Greece'), ('Greenland', 'Greenland'), ('Grenada', 'Grenada'), ('Guadeloupe', 'Guadeloupe'), ('Guam', 'Guam'), ('Guatemala', 'Guatemala'), ('Guernsey', 'Guernsey'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea Bissau'), ('Guyana', 'Guyana'), ('Haiti', 'Haiti'), ('Heard Island and McDonald Islands', 'Heard Island And Mcdonald Islands'), ('Holy See', 'Holy See'), ('Honduras', 'Honduras'), ('Hong Kong', 'Hong Kong'), ('Hungary', 'Hungary'), ('Iceland', 'Iceland'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Iran (Islamic Republic of)', 'Iran'), ('Iraq', 'Iraq'), ('Ireland', 'Ireland'), ('Isle of Man', 'Isle Of Man'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('Jamaica', 'Jamaica'), ('Japan', 'Japan'), ('Jersey', 'Jersey'), ('Jordan', 'Jordan'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kiribati', 'Kiribati'), ("Korea (the Democratic People's Republic of)", 'Democratic Peoples Republic Of Korea'), ('Korea (the Republic of)', 'Republic Of Korea'), ('Kuwait', 'Kuwait'), ('Kyrgyzstan', 'Kyrgyzstan'), ("Lao People's Democratic Republic", 'Lao Peoples Democratic Republic'), ('Latvia', 'Latvia'), ('Lebanon', 'Lebanon'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libya', 'Libya'), ('Liechtenstein', 'Liechtenstein'), ('Lithuania', 'Lithuania'), ('Luxembourg', 'Luxembourg'), ('Macao', 'Macao'), ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Malaysia', 'Malaysiamy'), ('Maldives', 'Maldives'), ('Mali', 'Mali'), ('Malta', 'Malta'), ('Marshall Islands', 'Marshall Islands'), ('Martinique', 'Martinique'), ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Mayotte', 'Mayotte'), ('Mexico', 'Mexico'), ('Micronesia (Federated States of)', 'Micronesia'), ('Moldova (the Republic of)', 'Moldova'), ('Monaco', 'Monaco'), ('Mongolia', 'Mongolia'), ('Montenegro', 'Montenegro'), ('Montserrat', 'Montserrat'), ('Morocco', 'Morocco'), ('Mozambique', 'Mozambique'), ('Myanmar', 'Myanmar'), ('Namibia', 'Namibia'), ('Nauru', 'Nauru'), ('Nepal', 'Nepal'), ('Netherlands', 'Netherlands'), ('New Caledonia', 'New Caledonia'), ('New Zealand', 'New Zealand'), ('Nicaragua', 'Nicaragua'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Niue', 'Niue'), ('Norfolk Island', 'Norfolk Island'), ('North Macedonia', 'North Macedonia'), ('Northern Mariana Islands', 'Northern Mariana Islands'), ('Norway', 'Norway'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), ('Palau', 'Palau'), ('Palestine, State of', 'Palestine'), ('Panama', 'Panama'), ('Papua New Guinea', 'Papua New Guinea'), ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Philippines', 'Philippines'), ('Pitcairn', 'Pitcairn'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Puerto Rico', 'Puerto Rico'), ('Qatar', 'Qatar'), ('Réunion', 'Réunion'), ('Romania', 'Romania'), ('Russian Federation', 'Russian Federation'), ('Rwanda', 'Rwanda'), ('Saint Barthélemy', 'Saint Barthélemy'), ('Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena'), ('Saint Kitts and Nevis', 'Saint Kitts And Nevis'), ('Saint Lucia', 'Saint Lucia'), ('Saint Martin (French part)', 'Saint Martin'), ('Saint Pierre and Miquelon', 'Saint Pierre And Miquelon'), ('Saint Vincent and the Grenadines', 'Saint Vincent And The Grenadines'), ('Samoa', 'Samoa'), ('San Marino', 'San Marino'), ('Sao Tome and Principe', 'Sao Tome And Principe'), ('Saudi Arabia', 'Saudi Arabia'), ('Senegal', 'Senegal'), ('Serbia', 'Serbia'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Singapore', 'Singapore'), ('Sint Maarten (Dutch part)', 'Sint Maarten'), ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'), ('Solomon Islands', 'Solomon Islands'), ('Somalia', 'Somalia'), ('South Africa', 'South Africa'), ('South Georgia and the South Sandwich Islands', 'South Georgia And The South Sandwich Islands'), ('South Sudan', 'South Sudan'), ('Spain', 'Spain'), ('Sri Lanka', 'Sri Lanka'), ('Sudan', 'Sudan'), ('Suriname', 'Suriname'), ('Svalbard and Jan Mayen', 'Svalbard And Jan Mayen'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Syrian Arab Republic', 'Syrian Arab Republic'), ('Taiwan (Province of China)', 'Taiwan'), ('Tajikistan', 'Tajikistan'), ('Tanzania, the United Republic of', 'Tanzania'), ('Thailand', 'Thailand'), ('Timor-Leste', 'Timor Leste'), ('Togo', 'Togo'), ('Tokelau', 'Tokelau'), ('Tonga', 'Tonga'), ('Trinidad and Tobago', 'Trinidad And Tobago'), ('Tunisia', 'Tunisia'), ('Turkey', 'Turkey'), ('Turkmenistan', 'Turkmenistan'), ('Turks and Caicos Islands', 'Turks And Caicos Islands'), ('Tuvalu', 'Tuvalu'), ('Uganda', 'Uganda'), ('Ukraine', 'Ukraine'), ('United Arab Emirates', 'United Arab Emirates'), ('United Kingdom of Great Britain and Northern Ireland', 'United Kingdom Of Great Britain And Northern Ireland'), ('United States Minor Outlying Islands', 'United States Minor Outlying Islands'), ('United States of America', 'United States Of America'), ('Uruguay', 'Uruguay'), ('Uzbekistan', 'Uzbekistan'), ('Vanuatu', 'Vanuatu'), ('Venezuela (Bolivarian Republic of)', 'Venezuela'), ('Viet Nam', 'Viet Nam'), ('Virgin Islands (British)', 'British Virgin Islands'), ('Virgin Islands (U.S.)', 'Us Virgin Islands'), ('Wallis and Futuna', 'Wallis And Futuna'), ('Western Sahara', 'Western Sahara'), ('Yemen', 'Yemen'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], max_length=100, verbose_name='Pais')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creado')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Ultima vez modificado')),
                ('actors', models.ManyToManyField(related_name='actors_content', to='category.actor', verbose_name='Actores')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='category.category', verbose_name='Categoria')),
                ('genders', models.ManyToManyField(related_name='genders_content', to='category.gender', verbose_name='Generos')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Temporada')),
                ('path', models.CharField(max_length=255, verbose_name='Ruta en disco duro de la temporada')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('was_added', models.BooleanField(default=False, verbose_name='Fue Agregada')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='catalogue.content', verbose_name='Temporadas')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to=apps.catalogue.helpers.generate_content_images_path, verbose_name='Url de la Imagen')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.content', verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta en disco duro del capitulo')),
                ('subtitle', models.FileField(blank=True, null=True, upload_to=apps.catalogue.helpers.generate_content_subtitles_path, verbose_name='Subtitulo')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='catalogue.content', verbose_name='Contenido')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='catalogue.season', verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Capitulo',
                'verbose_name_plural': 'Capitulos',
            },
        ),
    ]
