# Generated by Django 4.2 on 2023-07-13 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha completa de Estreno'),
        ),
        migrations.AlterField(
            model_name='content',
            name='release_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1900)], verbose_name='Año de Estreno'),
        ),
    ]
