# Generated by Django 4.2 on 2023-07-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_content_release_date_alter_content_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta en disco duro'),
        ),
    ]
