# Generated by Django 4.2.2 on 2023-07-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_content_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product',
            new_name='content',
        ),
    ]
