# Generated by Django 4.2.2 on 2023-07-26 23:03

import apps.catalogue.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_rename_product_image_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima vez modificado'),
        ),
        migrations.AlterField(
            model_name='image',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.content', verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(unique=True, upload_to=apps.catalogue.helpers.generate_content_images_path, verbose_name='Url de la Imagen'),
        ),
    ]
