# Generated by Django 4.2.2 on 2023-07-26 23:25

import apps.catalogue.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_content_update_date_alter_image_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='serie',
            new_name='content',
        ),
        migrations.AddField(
            model_name='season',
            name='path',
            field=models.CharField(default=None, max_length=255, verbose_name='Ruta en disco duro de la temporada'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='Ruta en disco duro del capitulo')),
                ('subtitle', models.FileField(upload_to=apps.catalogue.helpers.generate_content_subtitles_path, verbose_name='Subtitulo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('duration', models.CharField(max_length=255, verbose_name='Duración')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='catalogue.season', verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Capitulo',
                'verbose_name_plural': 'Capitulos',
            },
        ),
    ]
