# Generated by Django 4.2.2 on 2023-07-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_rename_serie_season_content_season_path_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta en disco duro del capitulo'),
        ),
        migrations.AlterField(
            model_name='season',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta en disco duro de la temporada'),
        ),
    ]
