# Generated by Django 4.2.2 on 2023-07-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_character_path_alter_season_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='path',
            field=models.CharField(blank=True, default='asd', max_length=255, null=True, verbose_name='Ruta en disco duro de la temporada'),
        ),
    ]
