# Generated by Django 4.2.2 on 2023-07-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_alter_season_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='path',
            field=models.CharField(max_length=255, verbose_name='Ruta en disco duro de la temporada'),
        ),
    ]
