# Generated by Django 4.2.2 on 2023-07-27 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_alter_season_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='catalogue.content', verbose_name='Temporadas'),
            preserve_default=False,
        ),
    ]
