# Generated by Django 4.2.2 on 2023-07-27 01:45

import apps.catalogue.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_character_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='catalogue.content', verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='character',
            name='subtitle',
            field=models.FileField(blank=True, null=True, upload_to=apps.catalogue.helpers.generate_content_subtitles_path, verbose_name='Subtitulo'),
        ),
        migrations.AlterField(
            model_name='content',
            name='format',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='content',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tamaño'),
        ),
    ]
