# Generated by Django 4.2.2 on 2023-07-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_alter_character_content_alter_character_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
