# Generated by Django 4.2.2 on 2023-07-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_season_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Duración'),
        ),
    ]
