# Generated by Django 4.2.2 on 2023-07-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_alter_character_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='duration',
        ),
        migrations.AddField(
            model_name='season',
            name='was_added',
            field=models.BooleanField(default=False, verbose_name='Fue Agregada'),
        ),
    ]
