# Generated by Django 4.2.2 on 2023-07-27 03:46

import apps.catalogue.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_remove_character_duration_season_was_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ruta en disco duro del capitulo')),
                ('subtitle', models.FileField(blank=True, null=True, upload_to=apps.catalogue.helpers.generate_content_subtitles_path, verbose_name='Subtitulo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='catalogue.content', verbose_name='Contenido')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='catalogue.season', verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Capitulo',
                'verbose_name_plural': 'Capitulos',
            },
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
