# Generated by Django 4.2.2 on 2023-07-27 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_chapter_delete_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='number_of_chapters',
        ),
    ]
